// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Namezr.Infrastructure.Data;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Namezr.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223131344_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalMode")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldConfigurationEntity", b =>
                {
                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FieldId", "VersionId");

                    b.HasIndex("VersionId");

                    b.ToTable("QuestionnaireFieldConfigurations");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireFields");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldValueEntity", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueSerialized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubmissionId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("QuestionnaireFieldValues");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireSubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("QuestionnaireSubmissions");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionnaireVersions");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldConfigurationEntity", b =>
                {
                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireFieldEntity", "Field")
                        .WithMany("Configurations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireVersionEntity", "Version")
                        .WithMany("Fields")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Namezr.Client.Studio.Questionnaires.Edit.QuestionnaireFileUploadFieldOptionsModel", "FileUploadOptions", b1 =>
                        {
                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityFieldId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityVersionId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("AllowedExtensions")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("MaxItemCount")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("MaxItemSize")
                                .HasColumnType("numeric");

                            b1.HasKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");

                            b1.ToTable("QuestionnaireFieldConfigurations");

                            b1.ToJson("FileUploadOptions");

                            b1.WithOwner()
                                .HasForeignKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");
                        });

                    b.OwnsOne("Namezr.Client.Studio.Questionnaires.Edit.QuestionnaireNumberFieldOptionsModel", "NumberOptions", b1 =>
                        {
                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityFieldId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityVersionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("MaxValue")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("MinValue")
                                .HasColumnType("numeric");

                            b1.HasKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");

                            b1.ToTable("QuestionnaireFieldConfigurations");

                            b1.ToJson("NumberOptions");

                            b1.WithOwner()
                                .HasForeignKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");
                        });

                    b.OwnsOne("Namezr.Client.Studio.Questionnaires.Edit.QuestionnaireTextFieldOptionsModel", "TextOptions", b1 =>
                        {
                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityFieldId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionnaireFieldConfigurationEntityVersionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsMultiline")
                                .HasColumnType("boolean");

                            b1.Property<int?>("MaxLength")
                                .HasColumnType("integer");

                            b1.Property<int?>("MinLength")
                                .HasColumnType("integer");

                            b1.HasKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");

                            b1.ToTable("QuestionnaireFieldConfigurations");

                            b1.ToJson("TextOptions");

                            b1.WithOwner()
                                .HasForeignKey("QuestionnaireFieldConfigurationEntityFieldId", "QuestionnaireFieldConfigurationEntityVersionId");
                        });

                    b.Navigation("Field");

                    b.Navigation("FileUploadOptions");

                    b.Navigation("NumberOptions");

                    b.Navigation("TextOptions");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldEntity", b =>
                {
                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireEntity", "Questionnaire")
                        .WithMany("Fields")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldValueEntity", b =>
                {
                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireFieldEntity", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireSubmissionEntity", "Submission")
                        .WithMany("FieldValues")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireSubmissionEntity", b =>
                {
                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireVersionEntity", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireVersionEntity", b =>
                {
                    b.HasOne("Namezr.Features.Questionnaires.Data.QuestionnaireEntity", "Questionnaire")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireEntity", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireFieldEntity", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireSubmissionEntity", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("Namezr.Features.Questionnaires.Data.QuestionnaireVersionEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
