name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ./Namezr/
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release ./Namezr/
      
#    - name: Publish artifacts
#      run: dotnet publish --no-build --configuration Release --output ./publish
#      
#    - name: Upload build artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: build-artifacts
#        path: ./publish
#        retention-days: 30

    # TODO: add this back when we have a nice way to setup the config
#    - name: Validate startup
#      run: dotnet run --no-build --project Namezr --configuration Release --launch-profile validate-startup

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
#    - name: Restore dependencies
#      run: dotnet restore
#      
#    - name: Build solution
#      run: dotnet build --no-restore --configuration Release
      
    # This ensures that only the test projects are restored and built
    - name: Run tests
#      run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --results-directory ./test-results
      run: dotnet test --configuration Release --verbosity normal --logger trx --results-directory ./test-results
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./test-results
        retention-days: 30